"""Add importance_level and llm_persona_prompt to Character model

Revision ID: cf3b3d4a95c8
Revises: 
Create Date: 2024-11-16 17:47:21.457147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3b3d4a95c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('llm_persona_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('llm_persona_prompt')
        batch_op.drop_column('importance_level')

    # ### end Alembic commands ###
