"""Add BookAnalysis Model

Revision ID: f89b0fbed7a0
Revises: cf3b3d4a95c8
Create Date: 2024-11-17 18:46:58.276869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89b0fbed7a0'
down_revision = 'cf3b3d4a95c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('character_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_name', 'author_name', name='unique_book_author')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_analysis')
    # ### end Alembic commands ###
